[package]
name = "reqwest"
version = "0.1.0"
authors = ["Bruce Schojan <bruce@basjr.com>"]
edition = "2018"

[dependencies]
sendgrid = { git = "https://github.com/baschoj/sendgrid-rs/" }
reqwest = "0.9"
